language: node_js

arch:
  - amd64
  - ppc64le

sudo: false

node_js:
  - "0.10"
  - "14"
  - "15"

jobs:
  exclude:
     - node_js: "0.10"
       arch: ppc64le

after_success:
 - if [[ ${TRAVIS_NODE_VERSION} == "0.10" ]]; then npm run coverage; fi;
